version: '3'

services:
  app:
    build:
      context: backend/.
      dockerfile: Dockerfile
      args:
        - Test:true
    environment:
      PYTHONPATH: '.'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      VK_CLIENT_ID: ${VK_CLIENT_ID}
      VK_CLIENT_SECRET: ${VK_CLIENT_SECRET}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      VK_REDIRECT_URI: ${VK_REDIRECT_URI}
      FRONTEND_FINISH_AUTH_URL: ${FRONTEND_FINISH_AUTH_URL}
    entrypoint: [ 'python', 'server.py' ]
    ports:
      - '80:8080'
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z.fips
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_DEFAULT_BUCKET};
      /usr/bin/mc policy set public myminio/${MINIO_DEFAULT_BUCKET};
      exit 0;
      "


volumes:
  pg-data:
  minio-data:
